pmndrs/xr

package.json

- Where to find the HMD position
- Parenting the VR camera and controllers to an object.

Added HMD position documentation

---

src/XR.tsx

reduces the renders to only when the controllers or addInteraction changes

memoize provider value

---

src/XR.tsx

Solves #6. See details in the issue.

Make sure inputSource is defined when adding hovering objects

---

src/Interactions.tsx

Creates and exports interfaces for Hover and Select components

Export Interaction Prop Interfaces

---

README.md

Min version source: https://twitter.com/rcabanier/status/1352549730534838272?s=21

[Docs] Updates hand tracking requirements

---

README.md
src/XR.tsx
src/webxr.tsx

A simple hook that abstracts the hit testing logic into something easier to use.

Added AR hit test hook

---

src/DefaultXRControllers.tsx
src/Hands.tsx
src/XR.tsx

blocked by https://github.com/pmndrs/three-stdlib/pull/50

Use three-stdlib

---

package.json
yarn.lock

Read more here:
https://github.com/mrdoob/three.js/releases/tag/r131

fix: three version up

---

src/XR.tsx

Missed this one in my last PR. my bad

Set isHandTracking initially instead of waiting for inputsourceschange event

---

examples/package.json
examples/yarn.lock

This pull request addresses the platform issues with scripts in `examples`, as reported in #55.

fix: use set directive in examples script

---

src/XR.tsx

Adds support for foveation with https://github.com/mrdoob/three.js/issues/22161.

feat(XR): support foveation

---

package.json

Prepare was missing prebuild and pack was missing files directive

Fix prepare and pack scripts

---

package.json
src/webxr/XRControllerModelFactory.js
src/webxr/XRHandMeshModel.js
yarn.lock

Import GLTFLoader from three-stdlib  

---

src/Interactions.tsx

Added intersection field to handlers other than hover/blue

---

src/webxr/XRControllerModelFactory.js
src/webxr/XRMotionControllers.js

Fixes #110 by vendoring and transpiling the `@webxr-input-profiles/motion-controllers` dependency. This issue actually persists in the three-stdlib package, so I'll want to make the same change there and hopefully do away with `src/webxr`.

fix(XRControllerModelFactory): vendor motion controller dep

---

src/XR.tsx

Cleans up useHitTest to create a hit test source on session init and cleanup on teardown.

refactor(useHitTest): subscribe to session, cleanup source init

---

src/DefaultXRControllers.tsx
src/Hands.tsx

Refactors `<Hands />` and `<DefaultXRControllers />` to create their respective models in R3F. Hardens against concurrency and HMR.

refactor: declaratively create controller models

---

src/Interactions.tsx

* Added `intersection` field to select/squeeze event handlers
* `intersections` field of select/squeeze event handlers now only has
unique intersections
Fixes #163

Fixed intersections for to select/squeeze event handlers

---

src/Interactions.tsx
src/XR.tsx

Added move event to Interactive and useInteraction

---

package.json
tsconfig.json
vite.config.js
yarn.lock

fix: unbundle for webpack tree-shaking, publish sourcemaps

---

package.json
tsconfig.json
vite.config.js

Reverts type changes from #170.

fix: regenerate types on build

---

src/XR.tsx

Fixes #172 by deferring to `WebXRManager` for session lifecycle in `XRButton`.

fix: handle session exit from device

---

src/Interactions.tsx
src/XR.tsx

Mirrors #183, backports into v4.

[v4] fix: fixed outdated callbacks

---

src/XR.tsx

Fixes #187 by invalidating global session cache.

fix(XR): purge session cache on exit

---

src/XR.tsx

Fixes #190 where XR was late to bind session listeners.

fix(XR): eagerly call sessionstart when late

---

src/XR.tsx
src/utils.ts

Also sync reference space type in global and context-store
Fixes #192

Automatically add provided reference space type to optionalFeatures

---

src/Controllers.tsx
src/Hands.tsx
src/Interactions.tsx
src/XR.tsx
src/XREvents.ts
src/utils.ts

#207 eagerly checking for out of sync hand tracking until underlying desync problem can be addressed.

fix: remove race condition around session events, init

---

src/XR.tsx

Missed one additional reference to the elusive "local-space"

tiny addition to doc change from #199

---

examples/package.json
examples/src/App.tsx
examples/src/demos/Hands.tsx
examples/src/demos/HitTest.tsx
examples/src/demos/Interactive.tsx
examples/src/demos/Player.tsx
examples/src/demos/Text.tsx
examples/src/demos/index.tsx
examples/src/styles.css.ts
examples/vite.config.ts
examples/yarn.lock
package.json
vite.config.js
yarn.lock

* Reinterpreted structure from [react-three-fiber/examples](https://github.com/pmndrs/react-three-fiber/blob/master/example/src/App.tsx)
* Used vanilla-extract instead of styled component
* XR examples is more standalone and ready for copy-paste

New examples structure

---

CONTRIBUTING.md

Following the #277 , I've prepared a contributing guide to ease up the process. It's not very fancy, but it's a good start

docs: contributing guide

---

docs/getting-started/development-setup.md

Is this a typo? I can't totally tell.

Fix typo: Floorless -> Flawlessly

---

docs/tutorials/guards.md

Use IfInSessionMode in code example

Update Guards doc page

---

packages/react/xr/src/pointer.tsx
packages/xr/src/vanilla/pointer.ts

related to #349 , this allows users to override the default material with their own

prioritize using user's provided materialClass for ray and cursor

---

docs/getting-started/all-components.md
packages/pointer-events/src/pointer.ts
packages/pointer-events/tests/browser/index.ts
packages/react/xr/src/default.tsx
packages/react/xr/src/events.tsx

Fix typo in "threshold"

---

docs/getting-started/faq.md
docs/handles/prebuild-handles.md
docs/handles/screen-handle-components.md

Fix handle package being named handles

---

docs/handles/screen-handle-components.md
packages/handle/src/screen/map.ts

Hi Bela! This PR fixes the map camera to behave more like the three map camera (e.g., for looking down at a map on a table, and moving across it).

Map controls

---

docs/tutorials/layers.md
packages/react/xr/src/layer.tsx

As of now in in the latest package version 6.6.14 the value of shape is updated. I have updated the docs accordingly. Please accept my pull request.

Update shape="equirectangular" to shape="equirect" for XRLayer doc
