pmndrs/xr

README.md

This fixes a few linting errors I was getting when using the code (with typescript), but more importantly fixes the camera position, ensuring it correctly positions itself relative to its parented object.
**Camera Position Issue**
When the parent object is positioned at `0, 0, 10` I would expect the camera to also be positioned at `0, 0, 10` once parented. However, the camera position was always static at `0, 0, 0`.
This seemed to be caused by `gl.xr.isPresenting` being present in the `useEffect` dependencies. I'm not sure why this was causing the issue - keen to know if anyone has any ideas. It seemed as though react wasn't detecting or registering any change in its value after it switched to true, but that's as far as I could get with it.
**Other minor fixes**
* Assigned the `parent` …

[docs] fixed camera parenting example

---

README.md

The immersive-web Motion Controllers repo changed its default branch name from `master` to `main`
so the link pointed to an outdated version, which could be easily missed by the reader

Update link to Motion Controllers repo main branch

---

src/Hands.tsx
src/XR.tsx
src/XRController.tsx

- added hands to the players group
- added a handtracking flag to the XR context based on the `inputsourceschange` event
I've setup examples (for easier testing).
The regular hands test we already have, with the changes:
https://elated-stonebraker-702075.netlify.app/hands
Repo can be found here: (`npm install` / `yarn` will setup the package correctly with my branch)
https://github.com/driescroons/react-xr-hands
I've also been working on a DefaultHandControllers component where the hand models are always shown, even when using controllers. It still needs a bit of work (different "poses" based on a button click, ...) but you'll get the basic idea. Could that also be something that could be added to react-xr?
https://elated-stonebraker-702075.netlify.app/default-hand-controllers
Let me know …

Adding hands to XRController

---

README.md

Fixes #53 by adding missing documentation for specialized interactives.

docs: add docs for RayGrab interactive

---

src/XR.tsx

Fixes #65 by invoking `onCreated` when specified.

fix: prevent overwriting XRCanvas bindings

---

src/XR.tsx
src/webxr/VRButton.js

Fixes #67 by refactoring `VRButton` to accept `sessionInit` as an argument like `ARButton`.

refactor: allow sessionInit to be specified in VR

---

src/XR.tsx

Using this with react-router and other stuff causes multiple buttons to be created when you change routes. This should either prevent that or give someone who has more time to dedicate to the problem a headstart in fixing the problem.

Prevent multiple VR/AR Buttons from being created

---

src/Hands.tsx

Hi there,
There is currently an issue where the HandModels are not being instantiated in some cases.
Here is a live demo to try with Oculus Browser:
https://codesandbox.io/s/react-xr-hands-demo-forked-uojb4
The reason is that `gl.xr.getHand` (called [here](https://github.com/pmndrs/react-xr/blob/449befa1e9e255bd7c12f03426f479b10a0381f0/src/XRController.tsx#L19)) has an inconsistent number of `children` (either 0 or 25), seemingly related to the amount of content in the scene (perhaps a race condition outside of the scope of this repo).
The problem is that the `HandModel` is instantiated only if the length of `children` is zero:
https://github.com/pmndrs/react-xr/blob/80971fbb88dd9846957af274750431de77ea83c0/src/Hands.tsx#L16
Instead, this fix proposes to check for an instance of …

fix: HandModel not being instantiated in some cases

---

src/webxr/VRButton.js

Fixes issue #93 
As described in the proposed solution in the issue, the unnecessary assignment has been deleted

fix(#93) entering vr will not overwrite the xr session feature list anymore

---

rollup.config.js

The library has no purpose when there's no webxr support

Used 'supports webxr' for babel preset env

---

src/Interactions.tsx

Previously there was an error "addInteraction is not a function" when trying to use interaction without AR/VR Canvas

Added console warning when XR context isn't initialized

---

src/Interactions.tsx

Fixes #97 by filtering event candidates, stopping at the first by default.
You can control this filtering via `state.raycaster.filter` as you can with R3F's built-in events.

feat(XRIntersectionEvent): filter event candidates via state.raycaster or stop on first hit

---

src/XR.tsx

Fixes #81 by listening to session changes re-emitted by WebXRManager.
Notably, in R3F v8, XRFrame is exposed through the built-in useFrame, so I'm inclined to deprecate this hook.

fix(useXRFrame): correctly react to session state changes

---

src/XR.tsx

Follows up #114 by deprecating `useXRFrame` as it is natively implemented in R3F v8.

chore(useXRFrame): add deprecation notice for v8

---

src/webxr/XRControllerModelFactory.js
src/webxr/XRHandMeshModel.js

Fixes the follow-up issue in #118 where some webxr modules import the GLTFLoader module from three-stdlib instead of resolving to the CJS flatbundle.

fix(webxr): import three-stdlib from flatbundle for cjs targets

---

src/XR.tsx

Ensures buttons are cleaned up with AR/VRCanvases. Exposes some of the internal XRButton behavior to enable granular customization with XRCanvas (related: #76).

fix(AR/VRCanvas): cleanup button on unmount

---

package.json
vite.config.js

Transpiles to ES 2018 for Node compat and uses mjs/js exts (alternatively type=module and cjs) to enable proper Node resolution.

fix: downlevel transpile, use correct node exts

---

src/webxr/HandModel.js
src/webxr/XRHandMeshModel.js

Prevents HandModel's children from recursively disposing its parent.

fix(HandModel): fix circular reference on dispose

---

README.md

On github the readme markdown image links for demos are not working, this PR changes the <a /> links to markdown []() links

Fix markdown demo links for github

---

package.json
src/Interactions.tsx
src/XR.tsx
src/XRController.tsx
src/XREvents.ts
yarn.lock

With https://github.com/three-types/three-ts-types/pull/218 and https://github.com/three-types/three-ts-types/pull/169 of `@types/three` 141, WebXR types are now ambient and pulled from `@types/webxr`.

refactor(types): use ambient WebXR types from @types/three

---

src/Interactions.tsx

Passes a fresh copy of R3F RootState when filtering events on interaction.

fix(InteractionManager): don't pass stale state on filter

---

src/Interactions.tsx
src/XR.tsx

Prefers to copy & re-use matrices in performance-sensitive code paths. Should hopefully remedy #30 if still current (needs reproduction).

fix: don't create matrices on useframe, re-use hitmatrix

---

src/Interactions.tsx
src/XR.tsx
src/XRController.tsx
src/XREvents.ts

Fixes https://github.com/pmndrs/react-xr/pull/142#discussion_r900048298 by making the `XREvent` and `XREventHandler` interfaces generic, and extending to `XRControllerEvent`, `XRManagerEvent`, and `XRSessionEvent` (built-in).

refactor: make XREvent and XREventHandler generic

---

src/DefaultXRControllers.tsx
src/Hands.tsx

Refactors `DefaultXRControllers` and `Hands` to manage its rays and models in R3F to prevent memory leaks. Also breaks up rays into a separate exported `Rays` component.

refactor: break up DefaultXRControllers, manage DefaultXRControllers and Hands in R3F

---

src/Interactions.tsx
src/XR.tsx

Continues #91. Adds `onSelectMissed` and `onSqueezeMissed` interaction handlers.

feat: add onSelectMissed and onSqueezeMissed interactions

---

src/DefaultXRControllers.tsx

Implements #87 by adding a `hideOnBlur` prop to `Ray` which would be passed from `hideRaysOnBlur` of `DefaultXRControllers`. This is disabled by default with rays persisting by default.
This would be more inline with menu ray representations and examples like https://threejs.org/examples/#webxr_vr_dragging.

feat(Ray): add option to hide on blur (show by default)

---

src/DefaultXRControllers.tsx
src/Hands.tsx

Fixes #161 by wrapping controllers' portal containers in a react fragment.

fix: wrap portals in fragment

---

examples/src/index.jsx
package.json
src/Interactions.tsx
vite.config.js
yarn.lock

Fixes a regression in transpiled output from #138 where dev-only plugins were wrongfully importing from `react/jsx-runtime` in ESM bundles. I've reverted that to use `React#createElement` and dropped `react-merge-refs` since it's effectively pinned with v2 being ESM-only (which can only clash with the React ecosystem).

fix: don't use jsx transform

---

vite.config.js

Mirrors #168 and disables automatic JSX transform which wrongly inexplicitly imports from `react/jsx-transform` in ESM bundles. This was enabled by default since #138.

fix: disable JSX transform

---

package.json
tsconfig.json
vite.config.js
yarn.lock

Unbundles lib output to enable Webpack's `sideEffects` optimization that works at the module level. Also enables sourcemaps for better debugging.

fix: unbundle for webpack tree-shaking, publish sourcemaps

---

src/Interactions.tsx
src/XR.tsx

By storing callback refs instead of callbacks themselves. Honestly I struggle to understand how it even worked before. Alternative approach would be as it was before v4, https://github.com/pmndrs/react-xr/blob/v3/src/Interactions.tsx#L157-L168. Current approach is better in a way that's handling null/undefined callbacks more correctly and efficiently, for instance an object with null callbacks with have data in interactions map but will be considered empty by `hasInteraction` (although it will require additional iteration)
Fixes #182

Fixed outdated callbacks

---

README.md

`local-space` doesn't exist, the available options are:
`type XRReferenceSpaceType = 'viewer' | 'local' | 'local-floor' | 'bounded-floor' | 'unbounded';`
Not sure if `local-floor` is the default though

Change input in readme to one which is an option

---

README.md
examples/src/index.tsx

Resolves #203.
The useHitTest example wasn't working correctly. This updated code disables the target's matrixAutoUpdate and applies the hitMatrix directly to its matrix property (as per this example: https://github.com/immersive-web/webxr-samples/blob/main/hit-test.html)

docs: prefer Matrix4#decompose in hit test example

---

package.json
vite.config.js
yarn.lock

I'm not sure how much of the WebXR API has this requirement, but at least when accessing the new Immersive AR ("passthrough") mode on a Quest headset, I need HTTPS to develop. Ran into this quickly while looking into some other things on the repository here and thought I'd push the change up if you're interested.
> ⚠️ **NOTE:** The browser will complain about an unrecognized HTTPS certificate when accessing a local development server for the first time. Accept the warnings, and you'll be able to access the examples.
*This contribution is funded by [R&D, The New York Times](https://rd.nytimes.com/).*

chore: set up SSL for development environment

---

README.md
examples/src/index.tsx
src/XR.tsx

Allows the user to handle failures to initialise - for example in firefox, XR support may be on, but there are no connected devices. Or, when the user rejects the prompt.

feat(XRButton): add `onError` prop for XR init

---

src/XR.tsx

Allows user-customizable button styles via `style`.

fix(XRButton): don't overwrite styles

---

src/XR.tsx

This should fix issue #213, but it might be a workaround for a more fundamental bug.
I recreated the problem without all the XR hand input event hassle. The issue currently arises when 2 array items are reversed in their order __and__ the react key prop of the array is used. An example of that is [here](https://github.com/bodo22/webxr-puzzle/blob/debug-primitive-swap/src/components/canvas/BuggyMinimalXR.jsx#L85).
The root of the Problem seems to be with [switchInstance](https://github.com/pmndrs/react-three-fiber/blob/master/packages/fiber/src/core/renderer.ts#L247) in react-three-fiber. In the specific buggy scenario, switchInstance removes the second element from the parent and adds as it the first. (in the first switch), then it removes that element from the parent in the second switch …

fix: hand mesh not visible after tracking lost/restored

---

src/XR.tsx

setSession currently reset foveation to 1 https://github.com/mrdoob/three.js/blob/b83bab0b213a0beb7643134021e1e693f1381dcf/src/renderers/webxr/WebXRManager.js#L331 so setFoveation needs to happen after it to work

fix: set foveation on session reset

---

src/Controllers.tsx
src/XRControllerModelFactory.ts

Following the [discussion](https://discord.com/channels/740090768164651008/749648291049898074/1070374102642213055) I vendored `XRControllerModelFactory` to `react-xr` along with some changes inside.
The main point of this is to fix problems with connecting/disconnecting different or same controllers, turns out webxr world is crazy full of quirks (who'd have thought). It all started in https://github.com/pmndrs/three-stdlib/pull/214: there I tried to fix a problem when you connect and disconnect controllers and it doesn't unsubscribe from `connected` event. Thing is, in three, `WebXRController` are only created twice and never recreated, but they spew out `connected/disconnected` events. Connecting and disconnecting same or different controllers before this fix would result in ever more …

fix: vendor and fix XRControllerModelFactory

---

README.md
src/XR.tsx

Our usecase is that we don't use `<VRButton />` because we don't use `react-dom` at all, but we still want to integrate with `react-xr` state and keep it in sync. Previously we just handled our own state, but that lead to a bunch of bugs when someone used `useXR` for the data that was out of sync. So I came with this utilities that allows to create your own headless button in any way you desire. @CodyJasonBennett what do you think?

feat: expose utilities for headless button creation

---

package.json

We recently started using corepack and yarn v3 and packages that doesn't have `pakcageManager` field but use `yarn` become a bit of a nuisance since it tries to use new one. This fixes it for corepack users

Support corepack

---

package.json
tsconfig.json

Fixes #264 by preferring the `.js` extension for ESM. I do not specify `package#exports` as Codesandbox resolution is a bit unstable there as of late.

fix: switch to type=module for Webpack <5

---

.eslintrc
examples/src/App.tsx
package.json
yarn.lock

* Installed the imported packages in ./examples/src/App.jsx issues viz: wrouter & use-error-boundary.
* Configured the eslintrc file to remove the following parsing error.

Fixing the ./examples/src/App.jsx issues

---

examples/vite.config.ts

Hey, @CodyJasonBennett , I saw that you've brought back path resolve in `examples/vite.config.ts`. I removed it on purpose so the codesandbox CI would work (it used to, but now it doesn't, not sure why). My idea is that examples are supposed to be run from the root with `yarn dev`, not from `examples` folder, and I highlighted it in https://github.com/pmndrs/react-xr/blob/master/CONTRIBUTING.md#run-locally for the newcomers. I apologize for not being clear enough in my PRs.
So, like, root vite.config will be responsible for local runs and examples/vite.config will be for codesandbox CI.
Example of codesandbox not working may be found in this PR, for instance
https://github.com/pmndrs/react-xr/pull/294
https://codesandbox.io/p/sandbox/examples-j88rj5

fix(examples): fix codesandbox build

---

.github/workflows/static.yml

mdx should no longer start with ./ in v2

chore: using pmndrs/docs v2

---

.github/workflows/static.yml

Add a GitHub icon to the upper right corner of the document for quick access to the repository.
[AS-IS]
- The document lacks a direct link to the GitHub repository
- Users have to manually navigate to the GitHub page
[TO-BE]
- A GitHub icon is added to the top right corner of the document
- Clicking the icon will directly link users to the associated GitHub repository

docs: Add GitHub icon to the top right of the document

---

examples/minecraft/src/Player.tsx
examples/minecraft/src/VRPlayerControl.tsx

This example wasn't quite patched after the last round of changes, so I've now modified it to reflect the latest iteration of the `useControllerLocomotion` hook

Fixing minecraft example after hook changes

---

docs/getting-started/all-hooks.md
docs/tutorials/gamepad.md
packages/react/xr/src/input.tsx

- Updated some outdated information on the gamepad.md tutorial
- Added some JSdoc and a better description for the `useXRInputSourceEvent` hook

docs: Update outdated info in the gamepad.md tutorial, and added a better description for the useXRInputSourceEvent hook and js doc

---

packages/react/xr/src/guard/session-mode.tsx

I found it quite unintuitive that useIsInSessionMode will always return true if neither allow nor deny is provided. With this simple change, one can quickly wrap components with `<IfInSessionMode>` without providing arguments to include the children only if any xr session is actually active.

useIsInSessionMode returns true by default only during active XR session

---

packages/handle/src/store.ts

When I was implementing a child class of HandleStore I found it challenging as some of the key parameters and methods are not accessible from inherited classes. I think we could update them as protected to allow child class accessibility while keeping it non-accessible by the usage classes.

Change some parameters in HandleStore to protected to unblock child class implementation

---

packages/react/xr/src/origin.tsx

In anticipation of play state support for Triplex WebXR I need to be able to disable userland XROrigin components when in "edit" state, but continue rendering them in the scene so their helper can be displayed in the scene.
This pull request adds `disabled` prop to the XROrigin component keeping it in line with what we did for the transform handles. Let me know if you think we should not render children when disabled (I'll annotate what I'm talking about).

Add disabled prop to XROrigin component

---

packages/react/xr/src/xr.tsx

In Triplex to support play states I need to be able to pick off userland XR context if it exists and then apply it to the bottom most XR provider in Triplex (so: Triplex always "owns" the bottom most XR state).
Userland XR state may not exist. If that's the case I still need the session to function, so this exposes a new XR store hook that won't throw an invariant if it's missing.
I've named it to discourage usage, but let me know if this tracks with your thoughts.

Add safe access XR store hook

---

packages/react/xr/src/layer.tsx
packages/xr/src/layer.ts
packages/xr/src/store.ts
packages/xr/src/vanilla/layer.ts

- added Object3D prop to XRLayerEntry
- depth sorting gets calculated in onBeforeRender, using distance to camera first and then falling back to renderOrder if equal

XRLayer: depth sorting prototype

---

packages/react/handle/src/handles/screen.tsx

Fixes the react hook for OrbitHandles and MapHandles

fix: correct disabled parameter logic in useApplyScreenCameraState
